[workspace]

resolver="2"

members = [
	"libs/lb/lb-rs",
	"libs/lb/lb-rs/libs/shared",
	"libs/lb/lb-rs/libs/test_utils",
	"libs/lb/lb-c-v2",
	"libs/lb/lb-c-v1",
	"libs/content/editor/egui_editor",
	"server/server",
	"clients/cli",
	"clients/egui",
	"clients/admin",
	"utils/dev-tool",
	"utils/releaser",
	"utils/winstaller",
]
