[workspace]

resolver="2"

members = [
	"libs/core",
	"libs/core/libs/shared",
	"libs/core/libs/test_utils",
	"libs/c_interface_v2",
	"libs/core_external_interface",
	"libs/editor/egui_editor",
	"server/server",
	"clients/cli",
	"clients/egui",
	"clients/admin",
	"clients/drive",
	"utils/dev-tool",
	"utils/releaser",
	"utils/winstaller",
]
