[package]
name = "admin"
version = "0.8.2"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
lockbook-core = { path = "../../libs/lb/core" }
dialoguer = { version = "0.10.1", features = ["fuzzy-select"] }
