[package]
name = "admin"
version = "0.6.0"
edition = "2021"

[dependencies]
structopt = "0.3.13"
lockbook-core = { path = "../../libs/core" }
dialoguer = { version = "0.10.1", features = ["fuzzy-select"] }
